### ISSUE TITLE
EXC BAD ACCESS

### ISSUE THREAD

**Issue by matrosovDev** [segment-integrations/analytics-ios-integration-mixpanel#8] opened 2016-04-06 19:20 UTC
Hey guys I have an issue on this part of code which is a part of analytics:

`- (void)persistQueue`
`{`
   ` [[NSUserDefaults standardUserDefaults] setValue:[self.queue copy] forKey:SEGQueueKey];`
   ` [[self.queue copy] writeToURL:self.queueURL atomically:YES];`
`}`

**Comment by f2prateek** [comment] 2016-04-06 19:21
Can you clarify more? Do you have a test case?

**Comment by matrosovDev** [comment] 2016-04-06 19:25
So this is not my app I just tested it to figure out what actually cause an issue and. One thing that I noticed that self.queue has about 5400 items of dictionaries. Let me try to find more cases.

Thanks for quick reply, I appreciate it.

**Comment by matrosovDev** [comment] 2016-04-06 19:36
It looks like app invokes this code:

```
[[SEGAnalytics sharedAnalytics] identify:[NSString stringWithFormat:@"%ld",
                                                  (long)customer.id]
                                          traits:traitsDict];
```

and then it crashes on a line `[[self.queue copy] writeToURL:self.queueURL atomically:YES];`

**Comment by matrosovDev** [comment] 2016-04-06 19:40
all self.properties has need data like a path for url: @"file:///Users/alex/Library/Developer/CoreSimulator/Devices/98D0B85B-0D69-4BAB-A7D5-4A542CDFF771/data/Containers/Data/Application/D2101E70-C666-41F0-A707-5BCFF54FD50A/Library/Application%20Support/segmentio.queue.plist"

and array that we try to write to a a url

**Comment by f2prateek** [comment] 2016-04-06 19:41
can you share the full error message?

**Comment by matrosovDev** [comment] 2016-04-06 19:44
So this is a log before app crashes:

```
2016-04-06 22:27:19.549 MyApp[18093:591334] [Crashlytics] Version 3.3.3 (81)
2016-04-06 22:27:19.754 MyApp[18093:591431] *** error: invalid size: (0.00 x 0.00). Both dimensions must be >= 1: <UIImage: 0x7e9f44d0>, {0, 0}
2016-04-06 22:27:19.814 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:19.815 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:19.817 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:19.846 MyApp[18093:591334] Failed to get token, error: Error Domain=NSCocoaErrorDomain Code=3010 "REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION" UserInfo={NSLocalizedDescription=REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION}
2016-04-06 22:27:19.864 MyApp[18093:591334] Failed to get token, error: Error Domain=NSCocoaErrorDomain Code=3010 "REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION" UserInfo={NSLocalizedDescription=REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION}
2016-04-06 22:27:21.721 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:21.721 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:21.722 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:22.318 MyApp[18093:591334] APPEARED !
2016-04-06 22:27:23.722 MyApp[18093:591334] *** -[__NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676bef7 -[__NSCFCalendar components:fromDate:] + 119
	1   CoreFoundation                      0x0676be09 -[_NSCopyOnWriteCalendarWrapper components:fromDate:] + 89
	2   MyApp                             0x0013ef52 -[MyAvailabilityScreen filterCalendarBasedOnDate] + 178
	3   MyApp                             0x0013e648 __44-[MyAvailabilityScreen loadAvaailables]_block_invoke + 840
	4   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	5   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	6   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	7   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	8   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	9   CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	10  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	11  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	12  GraphicsServices                    0x08110664 GSEventRunModal + 192
	13  GraphicsServices                    0x081104a1 GSEventRun + 104
	14  UIKit                               0x040c5eb9 UIApplicationMain + 160
	15  MyApp                             0x00316c1a main + 138
	16  libdyld.dylib                       0x06cf4a25 start + 1
)
2016-04-06 22:27:23.725 MyApp[18093:591334] *** -[__NSCFCalendar dateFromComponents:]: components cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676cfb7 -[__NSCFCalendar dateFromComponents:] + 119
	1   CoreFoundation                      0x0676cec2 -[_NSCopyOnWriteCalendarWrapper dateFromComponents:] + 82
	2   MyApp                             0x0013efbf -[MyAvailabilityScreen filterCalendarBasedOnDate] + 287
	3   MyApp                             0x0013e648 __44-[MyAvailabilityScreen loadAvaailables]_block_invoke + 840
	4   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	5   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	6   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	7   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	8   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	9   CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	10  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	11  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	12  GraphicsServices                    0x08110664 GSEventRunModal + 192
	13  GraphicsServices                    0x081104a1 GSEventRun + 104
	14  UIKit                               0x040c5eb9 UIApplicationMain + 160
	15  MyApp                             0x00316c1a main + 138
	16  libdyld.dylib                       0x06cf4a25 start + 1
)
2016-04-06 22:27:51.407 MyApp[18093:591334] APPEARED !
2016-04-06 22:27:52.618 MyApp[18093:591428] *** error: invalid size: (0.00 x 0.00). Both dimensions must be >= 1: <UIImage: 0x81acbce0>, {0, 0}
2016-04-06 22:27:52.645 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:52.646 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:52.647 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:53.801 MyApp[18093:591334] APPEARED !
2016-04-06 22:27:54.338 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:54.338 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:54.338 MyApp[18093:591334] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2016-04-06 22:27:56.393 MyApp[18093:591334] APPEARED !
2016-04-06 22:28:04.250 MyApp[18093:591334] *** -[__NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676bef7 -[__NSCFCalendar components:fromDate:] + 119
	1   CoreFoundation                      0x0676be09 -[_NSCopyOnWriteCalendarWrapper components:fromDate:] + 89
	2   MyApp                             0x00295e52 -[MySessionsViewController filterBasedOnState] + 178
	3   MyApp                             0x00295810 -[MySessionsViewController filterJSON:] + 704
	4   MyApp                             0x00294ec3 __51-[MySessionsViewController loadAvailabilities]_block_invoke + 291
	5   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	6   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	7   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	9   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	10  CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	11  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	12  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	13  GraphicsServices                    0x08110664 GSEventRunModal + 192
	14  GraphicsServices                    0x081104a1 GSEventRun + 104
	15  UIKit                               0x040c5eb9 UIApplicationMain + 160
	16  MyApp                             0x00316c1a main + 138
	17  libdyld.dylib                       0x06cf4a25 start + 1
)
2016-04-06 22:28:04.252 MyApp[18093:591334] *** -[__NSCFCalendar dateFromComponents:]: components cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676cfb7 -[__NSCFCalendar dateFromComponents:] + 119
	1   CoreFoundation                      0x0676cec2 -[_NSCopyOnWriteCalendarWrapper dateFromComponents:] + 82
	2   MyApp                             0x00295ebf -[MySessionsViewController filterBasedOnState] + 287
	3   MyApp                             0x00295810 -[MySessionsViewController filterJSON:] + 704
	4   MyApp                             0x00294ec3 __51-[MySessionsViewController loadAvailabilities]_block_invoke + 291
	5   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	6   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	7   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	9   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	10  CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	11  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	12  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	13  GraphicsServices                    0x08110664 GSEventRunModal + 192
	14  GraphicsServices                    0x081104a1 GSEventRun + 104
	15  UIKit                               0x040c5eb9 UIApplicationMain + 160
	16  MyApp                             0x00316c1a main + 138
	17  libdyld.dylib                       0x06cf4a25 start + 1
)
2016-04-06 22:28:04.714 MyApp[18093:591334] APPEARED !
2016-04-06 22:28:17.656 MyApp[18093:591334] APPEARED !
2016-04-06 22:28:19.976 MyApp[18093:591334] *** -[__NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676bef7 -[__NSCFCalendar components:fromDate:] + 119
	1   CoreFoundation                      0x0676be09 -[_NSCopyOnWriteCalendarWrapper components:fromDate:] + 89
	2   MyApp                             0x0013ef52 -[MyAvailabilityScreen filterCalendarBasedOnDate] + 178
	3   MyApp                             0x0013e648 __44-[MyAvailabilityScreen loadAvaailables]_block_invoke + 840
	4   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	5   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	6   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	7   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	8   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	9   CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	10  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	11  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	12  GraphicsServices                    0x08110664 GSEventRunModal + 192
	13  GraphicsServices                    0x081104a1 GSEventRun + 104
	14  UIKit                               0x040c5eb9 UIApplicationMain + 160
	15  MyApp                             0x00316c1a main + 138
	16  libdyld.dylib                       0x06cf4a25 start + 1
)
2016-04-06 22:28:19.978 MyApp[18093:591334] *** -[__NSCFCalendar dateFromComponents:]: components cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
(
	0   CoreFoundation                      0x0676cfb7 -[__NSCFCalendar dateFromComponents:] + 119
	1   CoreFoundation                      0x0676cec2 -[_NSCopyOnWriteCalendarWrapper dateFromComponents:] + 82
	2   MyApp                             0x0013efbf -[MyAvailabilityScreen filterCalendarBasedOnDate] + 287
	3   MyApp                             0x0013e648 __44-[MyAvailabilityScreen loadAvaailables]_block_invoke + 840
	4   MyApp                             0x002b649b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.49 + 43
	5   libdispatch.dylib                   0x06ca7363 _dispatch_call_block_and_release + 15
	6   libdispatch.dylib                   0x06cca9cd _dispatch_client_callout + 14
	7   libdispatch.dylib                   0x06caff7c _dispatch_main_queue_callback_4CF + 910
	8   CoreFoundation                      0x067921be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	9   CoreFoundation                      0x06750434 __CFRunLoopRun + 2356
	10  CoreFoundation                      0x0674f846 CFRunLoopRunSpecific + 470
	11  CoreFoundation                      0x0674f65b CFRunLoopRunInMode + 123
	12  GraphicsServices                    0x08110664 GSEventRunModal + 192
	13  GraphicsServices                    0x081104a1 GSEventRun + 104
	14  UIKit                               0x040c5eb9 UIApplicationMain + 160
	15  MyApp                             0x00316c1a main + 138
	16  libdyld.dylib                       0x06cf4a25 start + 1
)
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=16777216) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
(Recorded Frame) po traitsDict
Console is not supported for a recorded stack frame.
(lldb) po self.queue
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
MyApp(18093,0xb0115000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
```

**Comment by f2prateek** [comment] 2016-04-06 19:44
Also what version of the SDK are you using?

**Comment by f2prateek** [comment] 2016-04-06 19:45
I don't see any analytics references in the log, or references to bad access.

**Comment by matrosovDev** [comment] 2016-04-06 20:18
but the XCode stops on that line that try to writeURL

Using Analytics (3.0.7)

**Comment by matrosovDev** [comment] 2016-04-06 20:20
maybe it's simulator issue? I am not sure why debugger point me to that line. Maybe actually there is no log about issue of bad access. Let me add exception breakpoint

**Comment by matrosovDev** [comment] 2016-04-07 07:55
ok I've delete it a log as it does not contain needed information. let me check this issue on device, maybe it's also some XCode 7.3 issue.

**Comment by hankim813** [comment] 2016-04-18 21:08
Will close this issue for now since there's no reproducible test case here. Feel free to reopen if issue is on going.

**Closed by hankim813** 2016-04-18 21:08 UTC
